export const EVENTS = {
    NAVIGATE_TO_CODE_BLOCK: 'NAVIGATE_TO_CODE_BLOCK',
    INIT_BOOKMARKS: 'INIT_BOOKMARKS',
    PROMPT_STATE_COMPLETED: 'PROMPT_STATE_COMPLETED',
    CONVERSATION_DATA: 'CONVERSATION_DATA',
    TOGGLE_BOOKMARK: 'TOGGLE_BOOKMARK',
    GET_ALL_BOOKMARKS: 'GET_ALL_BOOKMARKS',
    OPEN_CHAT: 'OPEN_CHAT',
    HISTORY_STATE_UPDATED: 'HISTORY_STATE_UPDATED',
}

export const API = {
    INFER_METADATA: 'https://chatgpt.com/backend-api/conversation/textdocs/infer_metadata',
}
