export const EVENTS = {
    NAVIGATE_TO_CODE_BLOCK: 'NAVIGATE_TO_CODE_BLOCK',
    CODE_BLOCKS_UPDATE: 'CODE_BLOCKS_UPDATE',
    CONVERSATION_DATA: 'CONVERSATION_DATA',
    TOGGLE_BOOKMARK: 'TOGGLE_BOOKMARK',
    GET_ALL_BOOKMARKS: 'GET_ALL_BOOKMARKS',
    OPEN_CHAT: 'OPEN_CHAT',
}
